import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Menu, X } from 'lucide-react';
import { repository, type ModuleKey, type Team } from '@/lib/storage';
import { galleryService, vendorService } from '@/services/cmsServices';
import { articleHtml, eventDate, money, safeUrl, useDataRevision, whatsappUrl } from '@/lib/ux';
import { Dialog } from '@/components/shared/Dialog';
import { Empty, PageShell, TeamMark } from '@/components/shared/PublicUi';
import { FormField } from '@/components/admin/AdminUi';
import Home from './Home';
import Tournament from './Tournament';
import Registration, { ApplicationStatus } from './Registration';

const links = [['home', 'Home'], ['news', 'News'], ['tournament', 'Tournament'], ['teams', 'Teams'], ['vendors', 'Vendors'], ['gallery', 'Gallery'], ['about', 'About'], ['contact', 'Contact']];
const route = () => { try { return decodeURIComponent(location.pathname).replace(/^\/+|\/+$/g, '') || 'home'; } catch { return 'not-found'; } };
export default function PublicApp() {
  useDataRevision();
  const [page, setPage] = useState(route); const [open, setOpen] = useState(false); const focusPage = useRef(false);
  const settings = repository.getSettings(); const modules = settings.modules;
  const go = (next: string) => { history.pushState({}, '', next === 'home' ? '/' : `/${next}`); focusPage.current = true; setPage(next); setOpen(false); window.scrollTo(0,0); };
  useEffect(() => { const back = () => { focusPage.current = true; setPage(route()); setOpen(false); }; addEventListener('popstate', back); return () => removeEventListener('popstate', back); }, []);
  useEffect(() => { document.title = `${page === 'home' ? 'Home' : page.split('/')[0].replace(/-/g, ' ')} | ${settings.tournamentName}`; if (focusPage.current) document.getElementById('main-content')?.focus({ preventScroll: true }); }, [page, settings.tournamentName]);
  useEffect(() => { const icon = document.querySelector<HTMLLinkElement>('link[rel="icon"]'); if (icon) icon.href = settings.branding.favicon; }, [settings.branding.favicon]);
  const enabled = (id: string) => !(id in modules) || modules[id as ModuleKey];
  const navLinks = links.filter(([id]) => enabled(id));
  const closed = page === 'register' ? !modules.teamRegistration : page === 'register/vendor' ? !modules.vendorRegistration : !enabled(page.split('/')[0]);
  let content: ReactNode;
  if (closed) content = <PageShell title="Currently unavailable" eyebrow="Please check back"><p className="mb-5 text-white/70">This section is not open right now.</p><button className="btn-primary" onClick={() => go('contact')}>Contact the organiser</button></PageShell>;
  else if (page === 'home') content = <Home go={go}/>;
  else if (page === 'news') content = <News go={go}/>;
  else if (page.startsWith('news/')) content = <Article slug={page.slice(5)} go={go}/>;
  else if (page === 'teams') content = <Teams/>;
  else if (page === 'tournament') content = <Tournament/>;
  else if (page === 'vendors') content = <Vendors go={go}/>;
  else if (page === 'gallery') content = <Gallery/>;
  else if (page === 'register' || page === 'register/vendor') content = <Registration key={page} type={page === 'register' ? 'team' : 'vendor'} go={go}/>;
  else if (page === 'application-status') content = <ApplicationStatus/>;
  else if (page === 'contact') content = <Contact/>;
  else if (page === 'about') content = <PageShell title="Built for the culture" eyebrow="The story"><div className="grid gap-8 lg:grid-cols-2"><div><h2 className="display text-5xl font-black text-[#c8ff4b]">Local energy.<br/>Global feeling.</h2><p className="mt-6 text-lg leading-8 text-white/75">{settings.tournamentName} celebrates football as it is lived in our streets, schools and communities. A platform where talent, culture and opportunity share the same pitch.</p></div><div className="panel"><h2 className="display text-3xl font-bold">Plan your day</h2><p className="mt-5">{eventDate(settings.eventDate)}</p><p className="mt-3">{settings.venue}, {settings.city}</p><button className="btn-primary mt-6" onClick={() => go('contact')}>Get directions & contact</button></div></div></PageShell>;
  else content = <PageShell title="Page not found" eyebrow="404"><p className="mb-5">This page may have moved or is no longer available.</p><button className="btn-primary" onClick={() => go('home')}>Back to home</button></PageShell>;
  const navContent = <>{navLinks.map(([id,label]) => <button key={id} aria-current={page.split('/')[0] === id ? 'page' : undefined} onClick={() => go(id)} className={`min-h-11 text-left text-xs font-bold uppercase tracking-wider ${page.split('/')[0] === id ? 'text-[#c8ff4b]' : 'text-white/80'}`}>{label}</button>)}{modules.teamRegistration && <button className="btn-primary" onClick={() => go('register')}>Register Your Team</button>}</>;
  return <div className="min-h-screen"><a href="#main-content" className="skip-link btn-primary">Skip to content</a><header className="fixed inset-x-0 top-0 z-40 border-b border-white/10 bg-[#07100c]/95 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><button onClick={() => go('home')} aria-label="BEST5 home"><img src={settings.branding.mainLogo} alt="BEST5" className="h-12 w-12 rounded-lg object-cover"/></button><nav className="hidden items-center gap-5 xl:flex" aria-label="Main navigation">{navContent}</nav><button className="flex h-11 w-11 items-center justify-center xl:hidden" aria-label="Open navigation" aria-expanded={open} onClick={() => setOpen(true)}><Menu/></button></div>{open && <Dialog label="Main navigation" onClose={() => setOpen(false)}><div className="panel"><div className="mb-3 flex items-center justify-between"><b>Explore BEST5</b><button className="btn-secondary" aria-label="Close navigation" onClick={() => setOpen(false)}><X/></button></div><nav className="flex flex-col gap-2" aria-label="Mobile navigation">{navContent}</nav></div></Dialog>}</header>{content}<footer className="border-t border-white/10 bg-[#050b08] px-5 py-12"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3"><div><img src={settings.branding.lightLogo} alt="BEST5" className="h-16 w-16 rounded-xl object-cover"/><p className="mt-5 text-sm text-white/65">{settings.tournamentName}<br/>{settings.city}, South Africa</p><div className="mt-5 flex flex-wrap gap-4">{(['instagram','facebook','twitter','youtube','tiktok'] as const).filter(k => settings[k] && safeUrl(settings[k])).map(k => <a className="min-h-11 text-sm capitalize text-[#c8ff4b]" href={safeUrl(settings[k])} key={k} target="_blank" rel="noreferrer">{k === 'twitter' ? 'X' : k}</a>)}</div></div><div><h2 className="text-xs font-bold uppercase text-[#c8ff4b]">Explore</h2>{navLinks.map(([id,label]) => <button key={id} className="mt-2 block min-h-11 text-sm text-white/70" onClick={() => go(id)}>{label}</button>)}<button className="mt-2 min-h-11 text-sm text-[#c8ff4b]" onClick={() => go('application-status')}>Application status</button></div><div><h2 className="text-xs font-bold uppercase text-[#c8ff4b]">The big day</h2><p className="mt-5 text-sm text-white/70">{eventDate(settings.eventDate)}</p><p className="mt-3 text-sm text-white/70">{settings.venue}<br/>{settings.city}</p></div></div></footer></div>;
}

function News({ go }: { go: (page: string) => void }) {
  const [query,setQuery] = useState(''); const posts = repository.getPosts().filter(p => p.status === 'Published' && `${p.title} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
  return <PageShell title="News" eyebrow="BEST5 editorial"><label className="mb-8 block max-w-md text-sm">Search stories<input className="field mt-2" type="search" value={query} onChange={e => setQuery(e.target.value)}/></label><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{posts.map(post => <article key={post.id} className="overflow-hidden rounded-2xl border border-white/10"><img src={post.image} alt={post.title} className="h-56 w-full object-cover"/><div className="p-5"><p className="text-xs text-[#c8ff4b]">{post.category} · {post.date}</p><h2 className="display my-4 text-4xl font-bold uppercase">{post.title}</h2><p className="text-sm leading-7 text-white/70">{post.excerpt}</p><button className="btn-secondary mt-5" onClick={() => go(`news/${post.slug}`)}>Read story</button></div></article>)}</div>{!posts.length && <Empty text="No stories match your search. Try a different title or category."/>}</PageShell>;
}
function Article({ slug, go }: { slug: string; go: (page: string) => void }) {
  const post = repository.getPosts().find(p => p.slug === slug && p.status === 'Published');
  if (!post) return <PageShell title="Story unavailable" eyebrow="News"><button className="btn-primary" onClick={() => go('news')}>Back to news</button></PageShell>;
  return <PageShell title={post.title} eyebrow={`${post.category} · ${post.date}`}><article className="mx-auto max-w-3xl"><img src={post.image} alt={post.title} className="mb-8 max-h-[500px] w-full rounded-2xl object-cover"/><p className="mb-8 text-lg leading-8 text-white/75">{post.excerpt}</p><div className="post-editor leading-8" dangerouslySetInnerHTML={{ __html: articleHtml(post.content) }}/><button className="btn-secondary mt-10" onClick={() => go('news')}>Back to news</button></article></PageShell>;
}
function Teams() {
  const [group,setGroup] = useState('All groups'); const [selected,setSelected] = useState<Team|null>(null); const teams = repository.getTeams();
  return <PageShell title="Teams" eyebrow="The contenders"><div className="mb-8 flex flex-wrap gap-2">{['All groups', ...new Set(teams.map(t => t.group))].map(g => <button key={g} className={group === g ? 'btn-primary' : 'btn-secondary'} aria-pressed={group === g} onClick={() => setGroup(g)}>{g}</button>)}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{teams.filter(t => group === 'All groups' || t.group === group).map(team => <button key={team.id} className="card-lift panel text-left" onClick={() => setSelected(team)}><TeamMark team={team} large/><h2 className="display mt-5 text-3xl font-bold uppercase">{team.name}</h2><p className="mt-3 text-xs text-[#c8ff4b]">{team.group}</p><p className="mt-3 text-sm text-white/65">{team.city} · Captain: {team.captain}</p></button>)}</div>{!teams.length && <Empty text="Teams will appear after applications are approved."/>}{selected && <Dialog label={`${selected.name} team details`} onClose={() => setSelected(null)}><section className="panel max-w-xl"><div className="flex items-start justify-between gap-3"><div><TeamMark team={selected} large/><h2 className="display mt-3 text-4xl font-bold">{selected.name}</h2></div><button className="btn-secondary" aria-label="Close team details" onClick={() => setSelected(null)}><X/></button></div><p className="my-5">{selected.group} · {selected.city} · Captain: {selected.captain}</p><h3 className="display text-2xl">Squad</h3><ul className="mt-3 space-y-3">{selected.players.map(p => <li key={p.id} className="flex flex-wrap justify-between gap-3 rounded-xl bg-white/5 p-3"><b>{p.name}</b><span>#{p.number} · {p.position}</span></li>)}</ul></section></Dialog>}</PageShell>;
}
function Vendors({ go }: { go: (page: string) => void }) {
  const settings = repository.getSettings(); const vendors = vendorService.getVisible();
  return <PageShell title="Bring your brand" eyebrow="The BEST5 village"><div className="panel mb-8"><p className="max-w-2xl text-lg leading-8 text-white/75">Meet fans, build community and show up in the heart of {settings.city}'s football culture.</p><p className="my-5 font-bold">Stall fee: {money(settings.vendorStallFee)} per space</p>{settings.modules.vendorRegistration ? <button className="btn-primary" onClick={() => go('register/vendor')}>Book a stall</button> : <p className="text-white/65">Vendor applications are currently closed.</p>}</div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{vendors.map(v => <article key={v.id} className="overflow-hidden rounded-2xl border border-white/10">{v.image && <img src={v.image} alt={v.name} className="aspect-video w-full object-cover"/>}<div className="p-5"><p className="text-xs text-[#c8ff4b]">{v.category}</p><h2 className="display mt-3 text-3xl font-bold">{v.name}</h2><p className="my-4 text-sm leading-7 text-white/70">{v.description}</p>{safeUrl(v.website) && <a className="btn-secondary" href={safeUrl(v.website)} target="_blank" rel="noreferrer">Visit vendor</a>}</div></article>)}</div>{!vendors.length && <Empty text="The village lineup will be announced soon."/>}</PageShell>;
}
function Gallery() {
  const [selected,setSelected] = useState<{src:string;caption:string}|null>(null); const items = galleryService.getAll().filter(x => x.visible).sort((a,b) => a.order-b.order);
  return <PageShell title="Highlights" eyebrow="The atmosphere"><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{items.map(item => <button key={item.id} onClick={() => setSelected(item)} className={`overflow-hidden rounded-2xl border border-white/10 text-left ${item.featured ? "col-span-2" : ""}`}><img src={item.src} alt={item.caption || item.name} className="aspect-square w-full object-cover"/><span className="block p-3 text-xs text-white/70">{item.caption || item.name}</span></button>)}</div>{!items.length && <Empty text="The gallery is being prepared. Matchday highlights will appear here."/>}{selected && <Dialog label="Gallery image" onClose={() => setSelected(null)}><figure className="panel"><button aria-label="Close gallery image" className="btn-secondary mb-3" onClick={() => setSelected(null)}><X/>Close</button><img src={selected.src} alt={selected.caption} className="max-h-[70dvh] w-full object-contain"/><figcaption className="mt-3 text-center">{selected.caption}</figcaption></figure></Dialog>}</PageShell>;
}
function Contact() {
  const settings = repository.getSettings(); const [name,setName] = useState(''); const [email,setEmail] = useState(''); const [message,setMessage] = useState(''); const [topic,setTopic] = useState('Team registration'); const [ready,setReady] = useState(false);
  const mail = `mailto:${settings.contactEmail}?subject=${encodeURIComponent(`BEST5: ${topic}`)}&body=${encodeURIComponent(`${message}\n\nFrom: ${name}\nEmail: ${email}`)}`;
  return <PageShell title="Let's talk" eyebrow="Get in touch"><div className="grid gap-8 lg:grid-cols-2"><div><p className="mb-6 text-lg leading-8 text-white/75">Questions about teams, vendors, partnerships or matchday? Contact the BEST5 crew.</p><div className="flex flex-col items-start gap-4"><a className="btn-secondary" href={whatsappUrl(settings.whatsapp)} target="_blank" rel="noreferrer">Chat on WhatsApp</a><a className="btn-secondary" href={`tel:${settings.contactPhone.replace(/[^+\d]/g,'')}`}>{settings.contactPhone}</a><a className="break-all text-[#c8ff4b]" href={`mailto:${settings.contactEmail}`}>{settings.contactEmail}</a><a className="btn-secondary" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${settings.venue}, ${settings.city}`)}`} target="_blank" rel="noreferrer">Directions to {settings.venue}</a></div></div><form className="panel space-y-5" onSubmit={e => { e.preventDefault(); setReady(true); }}><FormField label="Your name"><input required autoComplete="name" className="field" value={name} onChange={e => { setName(e.target.value); setReady(false); }}/></FormField><FormField label="Email address"><input required type="email" autoComplete="email" className="field" value={email} onChange={e => { setEmail(e.target.value); setReady(false); }}/></FormField><FormField label="Topic"><select className="field" value={topic} onChange={e => setTopic(e.target.value)}>{['Team registration','Vendor spaces','Partnerships','Other'].map(x => <option key={x}>{x}</option>)}</select></FormField><FormField label="Your message"><textarea required rows={5} className="field" value={message} onChange={e => { setMessage(e.target.value); setReady(false); }}/></FormField><p className="text-sm text-white/65">Prepare your message here, then send it using your email app. Nothing is sent until you send the email.</p><button className="btn-primary">Prepare message</button>{ready && <div role="status" className="space-y-3"><p>Your message is ready. Open your email app to send it.</p><a className="btn-secondary" href={mail}>Open email app</a><p className="text-xs text-white/65">If no email app opens, use the WhatsApp link or email address alongside this form.</p></div>}</form></div></PageShell>;
}
