import { useState } from 'react';
import { repository, type Settings } from '@/lib/storage';
import { galleryService, mediaService, postService, settingsService } from '@/services/cmsServices';
import { removeOfficialTeam } from '@/services/workflowService';
import { AdminPageHeader, EmptyState, FormField, StatusBadge } from '@/components/admin/AdminUi';
import { MediaUploader } from '@/components/admin/MediaUploader';
import { TeamMark } from '@/components/shared/PublicUi';
import { confirmAction } from '@/components/shared/Confirm';
import { toast } from '@/components/shared/Toast';
import { useDataRevision, useUnsavedChanges } from '@/lib/ux';

function failed(err: unknown) { toast.error('Could not save',err instanceof Error ? err.message : 'Please try again.'); }
export function PostsPage({ navigate }: { navigate:(p:string)=>void }) {
  useDataRevision(); const [query,setQuery] = useState(''); const [status,setStatus] = useState('All'); const [category,setCategory] = useState('All'); const posts = repository.getPosts();
  const shown = posts.filter(p => (status === 'All' || p.status === status) && (category === 'All' || p.category === category) && p.title.toLowerCase().includes(query.toLowerCase()));
  return <><AdminPageHeader title="Posts" action={<button className="btn-primary" onClick={() => navigate('/admin/posts/new')}>New post</button>}/><div className="mb-6 grid gap-3 md:grid-cols-3"><FormField label="Search posts"><input type="search" className="field" value={query} onChange={e => setQuery(e.target.value)}/></FormField><FormField label="Status"><select className="field" value={status} onChange={e => setStatus(e.target.value)}>{['All','Draft','Published'].map(s => <option key={s}>{s}</option>)}</select></FormField><FormField label="Category"><select className="field" value={category} onChange={e => setCategory(e.target.value)}>{['All',...new Set(posts.map(p => p.category))].map(c => <option key={c}>{c}</option>)}</select></FormField></div><div className="grid gap-4 xl:grid-cols-2">{shown.map(p => <article key={p.id} className="panel"><div className="flex gap-4">{p.image && <img src={p.image} alt="" className="h-20 w-20 rounded-lg object-cover"/>}<div><h2 className="display text-2xl font-bold">{p.title || 'Untitled draft'}</h2><p className="my-2 text-xs text-white/65">{p.category} · {p.date}{p.featured ? ' · Featured' : ''}</p><StatusBadge value={p.status}/></div></div><div className="mt-5 flex flex-wrap gap-3"><button className="btn-secondary" onClick={() => navigate(`/admin/posts/${p.id}/edit`)}>Edit</button><button className="btn-secondary" onClick={() => { try { postService.setStatus(p.id,p.status === 'Published' ? 'Draft' : 'Published'); } catch (err) { failed(err); } }}>{p.status === 'Published' ? 'Unpublish' : 'Publish'}</button><button className="btn-secondary text-red-300" onClick={async () => { if (await confirmAction(`Delete “${p.title || 'Untitled draft'}”? This cannot be undone.`)) { try { postService.delete(p.id); } catch(err) { failed(err); } } }}>Delete</button></div></article>)}</div>{!shown.length && <EmptyState text="No posts match these filters. Clear your search or create a post."/>}</>;
}
export function MediaPage() {
  useDataRevision(); const items = mediaService.getAll();
  return <><AdminPageHeader title="Media library" action={<MediaUploader onUpload={file => mediaService.add({ ...file,id:crypto.randomUUID(),createdAt:new Date().toISOString() })}/>}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{items.map(item => <article key={item.id} className="panel"><img src={item.src} alt={item.name} className="aspect-square w-full rounded-xl object-cover"/><b className="mt-4 block truncate text-sm">{item.name}</b><p className="mt-2 text-xs text-white/65">{item.category}</p><div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" onClick={async () => { try { await navigator.clipboard.writeText(item.src); toast.success('Image link copied'); } catch { toast.error('Could not copy','Your browser did not allow clipboard access.'); } }}>Copy</button><button className="btn-secondary text-red-300" onClick={async () => { if (await confirmAction(`Remove ${item.name} from the library? Existing embedded images remain in their content.`)) { try { mediaService.delete(item.id); toast.success('Image removed'); } catch (err) { failed(err); } } }}>Delete</button></div></article>)}</div>{!items.length && <EmptyState text="Upload your first image to get started."/>}</>;
}
export function GalleryPage() {
  useDataRevision(); const items = galleryService.getAll().sort((a,b) => a.order-b.order);
  const save = (next:typeof items) => { try { galleryService.save(next.map((x,i) => ({ ...x,order:i }))); } catch(err) { failed(err); } };
  return <><AdminPageHeader title="Gallery" action={<MediaUploader category="Gallery" onUpload={file => galleryService.add({ ...file,id:crypto.randomUUID(),createdAt:new Date().toISOString(),caption:'',featured:false,visible:true,order:items.length })}/>}/><p className="mb-5 text-sm text-white/65">Captions, visibility and order save automatically.</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item,i) => <article key={item.id} className="panel"><img src={item.src} alt={item.caption || item.name} className="aspect-video w-full rounded-xl object-cover"/><div className="mt-4"><FormField label={`Caption for ${item.name}`}><input className="field" value={item.caption} onChange={e => save(items.map(x => x.id === item.id ? { ...x,caption:e.target.value } : x))}/></FormField></div><div className="mt-4 flex flex-wrap gap-4 text-sm"><label><input type="checkbox" checked={item.visible} onChange={e => save(items.map(x => x.id === item.id ? { ...x,visible:e.target.checked } : x))}/> Visible</label><label><input type="checkbox" checked={item.featured} onChange={e => save(items.map(x => x.id === item.id ? { ...x,featured:e.target.checked } : x))}/> Featured</label></div><div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" disabled={!i} onClick={() => { const next = [...items]; [next[i-1],next[i]] = [next[i],next[i-1]]; save(next); }}>Move earlier</button><button className="btn-secondary" disabled={i === items.length-1} onClick={() => { const next = [...items]; [next[i+1],next[i]] = [next[i],next[i+1]]; save(next); }}>Move later</button><button className="btn-secondary text-red-300" onClick={async () => { if (await confirmAction('Delete this gallery image? It will disappear from the public gallery.')) save(items.filter(x => x.id !== item.id)); }}>Delete</button></div></article>)}</div>{!items.length && <EmptyState text="Upload images to build your public gallery."/>}</>;
}
export function BrandingPage() {
  useDataRevision(); const settings = settingsService.get();
  return <><AdminPageHeader title="Branding"/><div className="grid gap-5 md:grid-cols-3">{(['mainLogo','lightLogo','favicon'] as const).map(key => <section className="panel" key={key}><h2 className="font-bold">{key.replace(/([A-Z])/g,' $1')}</h2><img src={settings.branding[key]} alt={key} className="my-5 h-32 w-full object-contain"/><MediaUploader category="Branding" onUpload={file => settingsService.update({ branding:{ ...settingsService.get().branding,[key]:file.src } })}/></section>)}</div><button className="btn-secondary mt-6" onClick={async () => { if (await confirmAction('Reset all branding images to the defaults?')) { try { settingsService.resetBranding(); } catch(err) { failed(err); } } }}>Reset to default</button></>;
}
export function TeamsPage() {
  useDataRevision(); const teams = repository.getTeams();
  return <><AdminPageHeader title="Official teams"/><p className="mb-5 text-sm text-white/65">Approve team applications to add teams. Group changes save immediately.</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{teams.map(t => <article className="panel" key={t.id}><div className="flex items-center gap-3"><TeamMark team={t}/><div><h2 className="font-bold">{t.name}</h2><p className="text-xs text-white/65">{t.captain} · {t.city}</p></div></div><div className="mt-4"><FormField label={`Group for ${t.name}`}><select className="field" value={t.group} onChange={e => { try { repository.saveTeams(teams.map(x => x.id === t.id ? { ...x,group:e.target.value } : x)); toast.success('Group updated'); } catch(err) { failed(err); } }}>{['Unassigned','Group A','Group B','Group C','Group D'].map(g => <option key={g}>{g}</option>)}</select></FormField></div><details className="mt-4 text-sm"><summary className="cursor-pointer py-2">Squad ({t.players.length})</summary><ul className="space-y-2">{t.players.map(p => <li key={p.id}>{p.number}. {p.name} · {p.position}</li>)}</ul></details><button className="btn-secondary mt-4 text-red-300" onClick={async () => { if (await confirmAction(`Remove ${t.name}? Its linked application will return to pending.`)) { try { removeOfficialTeam(t.id); } catch(err) { failed(err); } } }}>Remove from tournament</button></article>)}</div>{!teams.length && <EmptyState text="No official teams yet. Review team applications to add them."/>}</>;
}
const settingFields:[keyof Settings,string,string][] = [['tournamentName','Tournament name','text'],['eventDate','Event date','datetime-local'],['venue','Venue','text'],['city','City','text'],['prize','Prize money','number'],['numberOfTeams','Number of teams','number'],['affiliationFee','Affiliation fee','number'],['spotBookingFee','Spot booking fee','number'],['vendorStallFee','Vendor stall fee','number'],['contactEmail','Contact email','email'],['contactPhone','Contact phone','tel'],['whatsapp','WhatsApp number or link','text']];
export function SettingsPage() {
  const [settings,setSettings] = useState(settingsService.get()); const [saved,setSaved] = useState(JSON.stringify(settings)); const [error,setError] = useState(''); useUnsavedChanges(JSON.stringify(settings) !== saved);
  return <form onSubmit={e => { e.preventDefault(); try { settingsService.update(settings); setSaved(JSON.stringify(settings)); setError(''); } catch { setError('Could not save settings. Please try again.'); } }}><AdminPageHeader title="Settings" action={<button className="btn-primary">Save settings</button>}/>{error && <p role="alert" className="form-error mb-5">{error}</p>}<div className="panel grid gap-5 md:grid-cols-2">{settingFields.map(([key,label,type]) => <FormField key={key} label={label}><input required className="field" type={type} min={key === 'numberOfTeams' ? 2 : 0} step={type === 'number' ? 1 : undefined} value={String(settings[key])} onChange={e => setSettings({ ...settings,[key]:type === 'number' ? Number(e.target.value) : e.target.value })}/></FormField>)}<FormField label="Tournament mode"><select className="field" value={settings.lifecycle} onChange={e => setSettings({ ...settings,lifecycle:e.target.value as Settings['lifecycle'] })}>{['Pre Tournament','Matchday','Completed'].map(s => <option key={s}>{s}</option>)}</select></FormField></div></form>;
}
export function ModulesPage() {
  useDataRevision(); const settings = settingsService.get();
  return <><AdminPageHeader title="Modules"/><p className="mb-5 text-sm text-white/65">Changes save immediately. Disabling a page hides its navigation and makes its public URL unavailable. Existing applications can still be checked.</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{Object.entries(settings.modules).map(([key,value]) => <label key={key} className="panel flex items-center justify-between gap-4"><span className="capitalize">{key.replace(/([A-Z])/g,' $1')}</span><input type="checkbox" className="h-5 w-5 accent-[#c8ff4b]" checked={value} onChange={e => { try { settingsService.update({ modules:{ ...settings.modules,[key]:e.target.checked } }); } catch(err) { failed(err); } }}/></label>)}</div></>;
}
